Global:
  mode: train
  model: MobileNetV3_small_x1_0
  device: gpu
  device_id: 0
  seed: 1234
  output: output/mobilenetv3_small
  use_vdl: true
  dataset_dir: /home/nvidia/ai-lab/wukong_v15/data/itx

Train:
  model: MobileNetV3_small_x1_0
  num_classes: 7
  learning_rate: 0.001
  epochs: 50
  epochs_iters: null
  warmup_steps: null
  resume_path: null
  batch_size: 32
  lr_decay_epochs: [20, 40]
  log_interval: 10
  eval_interval: 1
  save_interval: 1
  pretrain_weight_path: ""
  dataset:
    name: ImageNet
    data_dir: /home/nvidia/ai-lab/wukong_v15/data/itx
    file_list: /home/nvidia/ai-lab/wukong_v15/data/itx/train.txt
    label_list: /home/nvidia/ai-lab/wukong_v15/data/itx/labels.txt
    shuffle: true
    transforms:
      - DecodeImage:
          to_rgb: true
          channel_first: false
      - ResizeImage:
          size: 224
      - NormalizeImage:
          scale: 1.0/255.0
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          channel_first: false

Evaluate:
  dataset:
    name: ImageNet
    data_dir: /home/nvidia/ai-lab/wukong_v15/data/itx
    file_list: /home/nvidia/ai-lab/wukong_v15/data/itx/val.txt
    label_list: /home/nvidia/ai-lab/wukong_v15/data/itx/labels.txt
    shuffle: false
    transforms:
      - DecodeImage:
          to_rgb: true
          channel_first: false
      - ResizeImage:
          size: 224
      - NormalizeImage:
          scale: 1.0/255.0
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          channel_first: false