Global:
  mode: train
  device: gpu
  device_id: 0
  seed: 1234
  save_dir: output
  use_vdl: true

Train:
  model: MobileNetV3_small
  num_classes: 10  # 请替换为实际的类别数
  learning_rate: 0.001
  epochs: 20
  batch_size: 32
  lr_decay_epochs: [10, 15]
  dataset:
    name: ImageNet
    data_dir: data/itx/images
    file_list: data/itx/train.json
    label_list: data/itx/labels.txt
    transforms:
      - RandomCrop: {crop_size: 224}
      - RandomHorizontalFlip:
      - Normalize: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}

Eval:
  dataset:
    name: ImageNet
    data_dir: data/itx/images
    file_list: data/itx/val.json
    label_list: data/itx/labels.txt
    transforms:
      - ResizeByShort: {short_size: 256}
      - CenterCrop: {crop_size: 224}
      - Normalize: