use_gpu: true
log_iter: 5
save_dir: /home/nvidia/ai-lab/wukong_v15/output/pp_tinypose_itx  # Updated to absolute path
snapshot_epoch: 10
weights: /home/nvidia/ai-lab/wukong_v15/output/pp_tinypose_itx/model_final.pdparams  # Updated to absolute path
epoch: 100
num_joints: &num_joints 6
pixel_std: &pixel_std 200
metric: KeyPointTopDownCOCOEval

data:
  type: CustomKeypointDataset
  module: wukong_v15.custom_dataset
use_nms: true
nms_threshold: 0.6
keypoint_threshold: 0.2
num_classes: 1
train_height: &train_height 256
train_width: &train_width 192
trainsize: &trainsize [*train_width, *train_height]
hmsize: &hmsize [48, 64]
flip_perm: &flip_perm []
use_ema: true
oks_sigmas: [0.025, 0.025, 0.025, 0.025, 0.025, 0.025]  # One sigma per keypoint

architecture: TopDownHRNet

TopDownHRNet:
  backbone: LiteHRNet
  post_process: HRNetPostProcess
  flip_perm: *flip_perm
  num_joints: *num_joints
  width: &width 40
  loss: KeyPointMSELoss
  use_dark: true

LiteHRNet:
  network_type: wider_naive
  freeze_at: -1
  freeze_norm: false
  return_idx: [0]

KeyPointMSELoss:
  use_target_weight: true
  loss_scale: 1.0

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    milestones: [70, 90]
    gamma: 0.1
  - !LinearWarmup
    start_factor: 0.001
    steps: 1000

OptimizerBuilder:
  optimizer:
    type: Adam
  regularizer:
    factor: 0.0
    type: L2

TrainDataset:
  !KeypointTopDownCocoDataset
    image_dir: images
    anno_path: train.json
    dataset_dir: /home/nvidia/ai-lab/wukong_v15/data/itx
    num_joints: *num_joints
    trainsize: *trainsize
    pixel_std: *pixel_std
    use_gt_bbox: True

EvalDataset:
  !KeypointTopDownCocoDataset
    image_dir: images
    anno_path: val.json
    dataset_dir: /home/nvidia/ai-lab/wukong_v15/data/itx
    num_joints: *num_joints
    trainsize: *trainsize
    pixel_std: *pixel_std
    use_gt_bbox: True
    image_thre: 0.5

TestDataset:
  type: CustomKeypointDataset
  module: wukong_v15.custom_dataset
  name: CustomKeypointDataset  # Add this line
  image_dir: images
  anno_path: val.json
  dataset_dir: /home/nvidia/ai-lab/wukong_v15/data/itx
  num_joints: *num_joints
  trainsize: *trainsize
  pixel_std: *pixel_std
  use_gt_bbox: True

worker_num: 2
global_mean: &global_mean [0.485, 0.456, 0.406]
global_std: &global_std [0.229, 0.224, 0.225]

TrainReader:
  sample_transforms:
    - RandomFlipHalfBodyTransform:
        scale: 0.25
        rot: 30
        num_joints_half_body: 3
        prob_half_body: 0.3
        pixel_std: *pixel_std
        trainsize: *trainsize
        upper_body_ids: [0, 1, 2]
        flip_pairs: *flip_perm
    - AugmentationbyInformantionDropping:
        prob_cutout: 0.5
        offset_factor: 0.05
        num_patch: 1
        trainsize: *trainsize
    - TopDownAffine:
        trainsize: *trainsize
        use_udp: true
    - ToHeatmapsTopDown_DARK:
        hmsize: *hmsize
        sigma: 2
  batch_transforms:
    - NormalizeImage:
        mean: *global_mean
        std: *global_std
        is_scale: true
    - Permute: {}
  batch_size: 8
  shuffle: true
  drop_last: false

EvalReader:
  sample_transforms:
    - TopDownAffine:
        trainsize: *trainsize
        use_udp: true
  batch_transforms:
    - NormalizeImage:
        mean: *global_mean
        std: *global_std
        is_scale: true
    - Permute: {}
  batch_size: 8

TestReader:  # Fix indentation here (remove 2 spaces)
  inputs_def:
    image_shape: [256, 192, 3]
  sample_transforms:
    - Decode: {}
    - AddImageKey: {}
    - TopDownAffine:
        trainsize: *trainsize
        use_udp: true
        with_joints: false
    - NormalizeImage:
        mean: *global_mean
        std: *global_std
        is_scale: true
    - Permute: {}
  batch_size: 1
  fuse_normalize: false
