Global:
  mode: train
  dataset_dir: data/itx/images
  train_list: data/itx/train.json
  val_list: data/itx/val.json
  label_list: data/itx/labels.txt
  save_dir: output/tinypose_itx
  num_epochs: 100
  train_batch_size: 8
  learning_rate: 0.001
  use_vdl: true

Model:
  type: keypoint_detection
  name: PP-TinyPose
  num_joints: 6  # Number of keypoints for ITX boards
